version: '3'

networks:
  back:
    driver: bridge

volumes:
  redis-data:
    driver: local

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://cache
    depends_on:
      - redis
    ports:
      - "3000:3000"
      - "9229:9299"
    networks:
      - back

  redis:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"
      - "6380:6380"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - back