version: '3'

networks:
  back:
    driver: bridge

volumes:
  redis-data:
    driver: local
  mongo-data:
    driver: local

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mongo://db/mininoise
      - PORT=3000
    depends_on:
      - mongo
      - rabbit
    ports:
      - "3000:3000"
      - "9229:9299"
    networks:
      - back

  mongo:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/var/lib/mongo
    networks:
      - back

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_URL=amqp://rabbit

    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      # - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
