version: '3'

networks:
  back:
    driver: bridge

volumes:
  redis-data:
    driver: local
  mongo-data:
    driver: local

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mongo://db/mininoise
      - MESSAGE_QUEUE=amqp://rabbitmq:rabbitmq@rabbitmq
      - PORT=3000
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "3000:3000"
      - "9229:9299"
    networks:
      - back
    links:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/var/lib/mongo
    networks:
      - back

  rabbitmq:
    image: "rabbitmq:3.7.4"
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_URL=amqp://rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
    networks:
      - back