version: '3'

networks:
  back:
    driver: bridge

volumes:
  redis-data:
    driver: local
  mongo-data:
    driver: local

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://cache
      - DATABASE_URL=mongo://db/mininoise
      - PORT=3000 
    depends_on:
      - redis
      - mongo
    ports:
      - "3000:3000"
      - "9229:9299"
    networks:
      - back

  redis:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"
      - "6380:6380"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - back

  mongo:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/var/lib/mongo
    networks:
      - back